fix: correctly update advanced relation metadata within brick (#761)
Error: metadata from an AdvancedManyToManyRelation or AdvancedManyToManyObjectRelation field within a brick wasn't stored
Caused by: ElementMetadata / ObjectMetadata was created with the "brickName~fieldName" notation, instead of the plain "fieldName"
Resolved with: passing the real field name via the callback method